apiVersion: apps/v1
kind: Deployment
metadata:
  name: orsem-django
  labels:
    app: orsem-django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orsem-django
  template:
    metadata:
      labels:
        app: orsem-django
    spec:
      containers:
        - name: orsem-django-container
          image: panghuuuuu/orsem-django:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: /cloudsql/stone-flux-442503-d1:us-central1:django
            - name: DB_NAME
              value: django
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
