apiVersion: apps/v1
kind: Deployment
metadata:
  name: orsem-django-v2
  labels:
    app: orsem-django
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orsem-django
      version: v2
  template:
    metadata:
      labels:
        app: orsem-django
        version: v2
    spec:
      containers:
        - name: orsem-django-container
          image: panghuuuuu/orsem-django:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_HOST
              value: /cloudsql/stone-flux-442503-d1:us-central1:django
            - name: DB_NAME
              value: django
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
          command:
            - "/cloud_sql_proxy"
            - "--dir=/cloudsql"
            - "--instances=stone-flux-442503-d1:us-central1:django"
            - "--credential_file=/secrets/cloudsql/credentials.json"
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
            - name: cloudsql-secrets
              mountPath: /secrets/cloudsql
      volumes:
        - name: cloudsql
          emptyDir: {}
        - name: cloudsql-secrets
          secret:
            secretName: cloudsql-credentials
